spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/digitail-twin-demo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: admin
    password: youngsun2020
    druid:
      filters: stat,wall,log4j2
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 2
      filter:
        log4j2:
          statement-executable-sql-log-enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath*:com/ylzinfo/brt/privilege/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  config-location:

logging:
  file: ../digitail-twin-demo/logs/digitail-twin-demo.log
  level:
    com.gs.*: info
